name: release workflow

on:
  # no longer run release on every PR to main, instead just on schedule
  # push:
  #     branches:
  #         main
  workflow_dispatch:
    inputs:
      hotfix_release:
        description: "Use the hotfix workflow"
        required: true
        type: boolean
        default: false
  # schedule:
  #   # Monday-Thursday at 10 AM CST (16:00 UTC)
  #   - cron: "0 16 * * 1-4"
  #   # Monday-Thursday at 2 PM CST (20:00 UTC)
  #   - cron: "0 20 * * 1-4"
  #   # Friday at 10 AM CST (16:00 UTC)
  #   - cron: "0 16 * * 5"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check-for-open-hotfixes:
    # Skip this job if this is a hotfix release
    if: ${{ !inputs.hotfix_release }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.AVANTBOT_SSH_KEY }}
      - name: Check for open hotfix PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "==============================================================="
          echo "              CHECKING FOR OPEN HOTFIX PRs                      "
          echo "==============================================================="

          # Get all open PRs to main and filter for hotfix label
          pr_data=$(gh pr list --base main --json number,title,url,labels | \
                   jq '[.[] | select(.labels[].name == "hotfix")]')
          hotfix_count=$(echo "$pr_data" | jq length)

          if [ "$hotfix_count" -gt 0 ]; then
            echo "❌ Error: Found $hotfix_count open hotfix PR(s) to main"
            echo ""
            echo "Open Hotfix PRs:"
            echo "$pr_data" | jq -r '.[] | "• \(.title) -> \(.url)"'
            echo ""
            echo "Cannot proceed with release while hotfix PRs are pending."
            echo "Next steps:"
            echo "1. Review and merge all open hotfix PRs listed above"
            echo "2. Run this workflow again"
            echo "==============================================================="
            exit 1
          fi

          echo "✅ No open hotfix PRs found"
          echo "==============================================================="

  prod-release-deploy:
    needs: check-for-open-hotfixes
    runs-on: ubuntu-latest
    if: ${{ !inputs.hotfix_release || success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "to-deploy"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -D semantic-release @semantic-release/git @semantic-release/github

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Push deployed tag
        run: |
          git tag -f deployed
          git push origin deployed -f

      - name: Push hotfix tag
        if: ${{ inputs.hotfix_release }}
        run: |
          git tag -f "hotfix-${{ github.sha }}"
          git push origin "hotfix-${{ github.sha }}" -f
